### ISSUE TITLE
Feature request: Add custom macro or function to define a custom git forge.

### ISSUE THREAD

**Issue by jgarte** [sshaw/git-link#104]
Hi,

In the name of extensibility, I'd like to request a macro or way of creating my own handler easily for a custom git forge.

For example I tried to use `git-link` on this forge and it failed:

https://git.cyberia.club/cyberia/capsul-flask

**Comment by sshaw** [comment]
Have you tried [this](https://github.com/sshaw/git-link#building-links-and-adding-services)?

**Comment by jgarte** [comment]
So, you're saying to just add a entry to that alist for cyberia with a custom function:

`git-link-cyberia`, for example?

**Comment by sshaw** [comment]
> So, you're saying to just add a entry to that alist for cyberia with a custom function:

Yes. And given the arguments passed to that function you should be able to generate the link.

**Comment by sshaw** [comment]
Closing as the documentation should be sufficient. Feel free to reopen if you are still experiencing issues.
