### ISSUE TITLE
Fails to resolve insteadOf directives when looking up remote URLs

### ISSUE THREAD

**Issue by ilmari** [sshaw/git-link#111]
Given my `~/.gitconfig` has:

```
[url "git@github.com:"]
	insteadOf = gh:
```
and I do `git clone gh:sshaw/git-link`, open `git-link/git-link.el` and run `M-x git-link`, I get the error message `No handler found for gh`

This is because `git-link--remote-url` calls `git config remote.{name}.url` which returns the raw URL.
Instead it should be calling `git remote get-url {name}`, which resolves `insteadOf` directives.

This version works for me:

```elisp
(defun git-link--remote-url (name)
  (car (git-link--exec "remote" "get-url" name)))
```

**Comment by sshaw** [comment]
Thanks @ilmari.  This has been fixed on master. Check it out!
