### ISSUE TITLE
Feature Request: Choose from multiple remotes

### ISSUE THREAD

**Issue by jgarte** [sshaw/git-link#113]
Hi,

If I have multiple remotes, I'd like to choose from a particular one to construct the link.

What do you think of this feature request?

**Comment by sshaw** [comment]
Hi, this behavior already exists. From [the docs](https://github.com/sshaw/git-link/tree/aded95807f277f30e1607313bdf9ac9a016a2305#usage): 

> Functions can be called interactively (M-x git-link) or via a key binding of your choice
> ...
> With a single prefix argument prompt for the remote's name. Defaults to "origin".

The prompt uses `completing-read`. 

Does this differ from what you were thinking?

**Comment by sshaw** [comment]
Closing as this functionality already exists. Feel free to reopen if what you're suggesting is indeed different.
