### ISSUE TITLE
git-link-commit in master 

### ISSUE THREAD

**Issue by kaushalmodi** [sshaw/git-link#12]
Hi,

When I try to select a region and call `git-link-commit`, I get the error

> Point is not on a commit hash

Instead of that, can you return the link to the selected lines from the **latest** commit?

Most of the time, I need to send reference to a piece of code from my master (latest commit). But that code might change in the future and the line references might change. So I prefer to link to the links in that specific commit even if that's the master.

**Comment by sshaw** [comment]
Resolved by a570765.
