### ISSUE TITLE
Feature request: git-link-open-homepage

### ISSUE THREAD

**Issue by psibi** [sshaw/git-link#124]
I have a use case, where *sometimes* I would want to open the repository's homepage in browser.

Currently, we have this variable `git-link-open-in-browser`, but that will always make it open via the browser.

I can also probably implement this if there are no objections, once I find some spare time. Would you be open to supporting a separate interactive function for this ?

**Comment by sshaw** [comment]
So you want to call `git-link-homepage` and sometimes you want it to copy and other times you want it to copy _and_ open the page in the browser?

**Comment by sshaw** [comment]
>  So you want to call git-link-homepage and sometimes you want it to copy and other times you want it to copy and open the page in the browser?

What determines when you want it to open vs just copy the URL?

**Comment by psibi** [comment]
> So you want to call git-link-homepage and sometimes you want it to copy and other times you want it to copy and open the page in the browser?

Yes

> What determines when you want it to open vs just copy the URL?

When someone is asking me to send a repository link (which seems to happening more recently these days), I send them the copy of the URL. When I want to visit the homepage because I want to probably browse some issues - I will use the `git-link-open-homepage`.

**Comment by sshaw** [comment]
What about adding a prefix argument to `git-link-homepage` to force an open? 🔗

**Comment by psibi** [comment]
Yeah, agree. That would be more idiomatic.

**Comment by psibi** [comment]
This seems to be working fine for my usecase: https://github.com/sshaw/git-link/pull/125

**Comment by sshaw** [comment]
Thanks. 

Instead of a prefix arg of 1 what do you think about using a double-prefix (<kbd>Ctrl-u Ctrl-u</kbd>) since that's what `git-link` uses. Makes it more consistent across functions. 

Seems that single prefix is what we want but that prompts for remote which I _guess_ is necessary to keep inline with `git-link` since homepage could be based on remote name.
