### ISSUE TITLE
Transient integration is breaking doomemacs setup

### ISSUE THREAD

**Issue by vlnn** [sshaw/git-link#129]
After upgrading to latest version of git-link doom emacs starts to fail during the start. 

```
Warning (initialization): An error occurred while booting Doom Emacs:

Symbol's function definition is void: transient-prefix
To ensure normal operation, you should investigate and remove the
cause of the error in your Doom config files. Start Emacs with
the '--debug-init' option to view a complete error backtrace.
Error (doom-after-init-hook): Error running hook "doom-display-benchmark-h"
because: (wrong-type-argument hash-table-p nil)

```

It looks like the issue below somehow got to the git-link, as after disabling it in the packages emacs is accessible again.

https://github.com/magit/transient/issues/254

**Comment by jplindstrom** [comment]
One more data point: Happens with `use-package` with `straight` too.

**Comment by dpassen** [comment]
`use-package` with `elpaca` also fails to install the latest.

**Comment by sshaw** [comment]
@blahgeek ideas on how to fix? 

Reverted the commits for now. It seems no ones uses MELPA stable?

**Comment by sshaw** [comment]
> Reverted the commits for now. It seems no ones uses MELPA stable?

Well other options too. 

How are you pulling in this package @dpassen @jplindstrom @vlnn @vespesa❓

**Comment by necaris** [comment]
Note: using the version without the Transient integration seems to work for me -- using Doom Emacs, the following line in my `packages.el` pins the commit:
```elisp
  (package! git-link :pin "fd33c3f7692bdf4b039afaa88cf07580429043ad")
```
It seems that for compatibility with Emacs 29.x you need a [slightly different autoload declaration for Transient](https://github.com/magit/transient/issues/280#issuecomment-2019214088)?

**Comment by vlnn** [comment]
Revert (and moving transient functionality to another repo) helped in my case, so pinning to previous commits should not be needed anymore. Thanks @sshaw!
