### ISSUE TITLE
function with identical behavior to git-link that uses current commit instead of branch

### ISSUE THREAD

**Issue by IvanMalison** [sshaw/git-link#24]
Using a branch name is fragile because it can break if the branch is updated to point to a new sha. Seems like it would be nice to use `git rev-parse HEAD` to link to the current ref (which is immutable and therefore less fragile).

**Comment by IvanMalison** [comment]
oops. looks like this is what git-link-use-commit does. Sorry

**Comment by sshaw** [comment]
Also checkout the [`git-link-use-commit` option](https://github.com/sshaw/git-link#git-link-use-commit).
