### ISSUE TITLE
tracking instead of origin as default

### ISSUE THREAD

**Issue by unhammer** [sshaw/git-link#26]
I often have several remotes where none are named origin; but there's typically one that's the tracking remote for that branch. 

When called with no prefix arg, it'd be nice to default to the tracking one; if there's no tracking remote, then try origin if possible; if not, just pick one of the remaining possibilities.

**Comment by sshaw** [comment]
Hummm, seems like a good idea, maybe it should have been the default from the beginning :speak_no_evil:. Essentially you're suggesting `git-link`'s remote should default to:

```
git config --get branch.$(git symbolic-ref --short HEAD).remote
```

Right?

We have ways to do this now, just a bit more explicit:

1. `git-link-default-remote` - it won't work as you have various defaults depending on the repo/branch?
1. Why not just [set `git-link.remote`](https://github.com/sshaw/git-link#local)?

How would you reconcile those two options with what you're suggesting?

**Comment by unhammer** [comment]
Perhaps change the default

    (defvar git-link-default-remote 'tracking-guess 
      "Name of the remote to link to, or the symbol 'tracking-guess to guess from one of the available remotes (prioritizing the tracking remote).")

But let any .git/config settings override?

**Comment by sshaw** [comment]
Currently `git-link` checks **1** `git config --get git-link.remote` then **2** `git-link-default-remote`. I'm thinking that a release with your suggestion will default `git-link-default-remote` to `nil` and `git config --get branch.xxxx.remote` will be **3**.

For those that have  `git-link-default-remote` set to something besides `"origin"` things will continue to work as before. For those that don't `git-link` will (likely?) still default to `"origin"` or, better yet, the branch's remote.

**Comment by unhammer** [comment]
Sounds good to me :)

**Comment by sshaw** [comment]
@unhammer checkout the [default_to_tracking branch](https://github.com/sshaw/git-link/tree/defult_to_tracking).

**Comment by unhammer** [comment]
Nice :)

**Comment by sshaw** [comment]
This is now part of the [v0.4.0 release](https://github.com/sshaw/git-link/releases/tag/v0.4.0).
