### ISSUE TITLE
git link breaks on repositories accessed through custom port

### ISSUE THREAD

**Issue by kbrooks** [sshaw/git-link#32]
At my company we host our git repositories on gitlab and access them through port 2222.
For example, the url config on one of our repositories is:
	url = ssh://git@gitlab.imshealth.com:2222/tools/ImsHealth.Automation.git

The function git-link--remote-host fails when there is a port, simply returning "2222".

https://github.com/sshaw/git-link/blob/master/git-link.el#L163

It should return "gitlab.imshealth.com".

**Comment by kbrooks** [comment]
I've started working on a fix for this issue

**Comment by sshaw** [comment]
Hey, actually I forgot all the URL styles that were supported (I really need to add some tests!) so that didn't work either 😿 but [checkout this branch](https://github.com/sshaw/git-link/tree/url-with-port) and let me if that fixes it.

Thanks.

**Comment by kbrooks** [comment]
That works for me

**Comment by sshaw** [comment]
Fixed in `v0.4.2`.
