### ISSUE TITLE
Invalid link `git@github.com` when gitconfig url is ssh and doesn't end in .git

### ISSUE THREAD

**Issue by CestDiego** [sshaw/git-link#35]
I had this in my gitconfig:

```
[remote "origin"]
	url = git@github.com:CestDiego/spacemacs
	fetch = +refs/heads/*:refs/remotes/origin/*
```

And while normally it works for other purposes such as pulling and other things, git link thinks that it's a url and tries to link me to a `http://git@github.com/CestDiego/Spacemacs` which of course doesn't have a handler and then errors out by saying, `no handler for git@github`

**Comment by sshaw** [comment]
Hi, what version of git-link and Emacs are you using? 

I could not reproduce this with 0.4.2 (Emacs 24.4.1) though the URL matching regex did change in 0.4.2.

**Comment by sshaw** [comment]
@CestDiego can you provide the version of git-link and Emacs that caused this error?

**Comment by CestDiego** [comment]
@sshaw it works in the latest version of git-link. I'm sorry I can't report on what version I had before as I updates today
