### ISSUE TITLE
Cannot parse tramp filenames

### ISSUE THREAD

**Issue by cswarth** [sshaw/git-link#49]
It would be great if this package could deal with tramp-mode filenames that look like `/ssh:aws-dev:/home/ubuntu/somedir/main.go`
When I called `git-link` I get the message `Can’t figure out what to link to`

**Comment by sshaw** [comment]
Yes, very good idea. 

The problem seems to be with [running `git rev-parse --show-top-level`](https://github.com/sshaw/git-link/blob/472af75eca7aba42a1934f408c4bda55e34c9dcf/git-link.el#L198-L199). Your buffer is remote, but this is ran locally. 

Any idea how to fix?

**Comment by sshaw** [comment]
It looks like [using `start-file-process`](https://www.gnu.org/software/emacs/manual/html_node/tramp/Remote-processes.html) will run on the remote server when buffer is a tramp file.

**Comment by juergenhoetzel** [comment]
Had the same issue. Proposed fix: #54
