### ISSUE TITLE
Infer revision used when visiting buffer created by vc-find-revision

### ISSUE THREAD

**Issue by IvanMalison** [sshaw/git-link#52]
I like to use `vc-revision-other-window` to checkout old versions of a file in emacs. It would be awesome if git-link understood what was happening in this case and would like to the appropriate revision/filename when I use it from one of these buffers.

**Comment by sshaw** [comment]
Good idea. Do you know what `vc-mode` function to call? 

Currently [git-timemachine](https://github.com/pidu/git-timemachine/]) is supported.
