### ISSUE TITLE
Test fails on recent Emacs version

### ISSUE THREAD

**Issue by juergenhoetzel** [sshaw/git-link#55]
Emacs 26.1:
```

In end of data:
git-link.el:495:1:Warning: the following functions are not known to be
    defined: dired-file-name-at-point, magit-file-at-point, string-blank-p
emacs -Q --batch -L . -l ert -l git-link-test.el -f ert-run-tests-batch-and-exit
Args out of range: "", 1, nil
```
Changelog for Emacs > 25.1:

> 
>     * lisp/url/url-parse.el (url-path-and-query): Do not artificially turn empty
>     path and query into nil path and query, respectively.

Dissecting empty path now returns "" instead of nil.

It would seem advisable to add more recent Emacs releases to the Travis test matrix?
Also the `emacs-snapshot` used is also outdated:

```
Setting environment variables from .travis.yml
$ export EMACS=emacs-snapshot
...
0.01s$ emacs --version
GNU Emacs 24.3.1

```

**Comment by sshaw** [comment]
> It would seem advisable to add more recent Emacs releases to the Travis test matrix?

Indeed. I think I looked into this but only 24.X packages are available, even with updated sources. 

Thanks though. I will see what I can do.
