### ISSUE TITLE
Control over whether to link to a file in a branch or a file in a commit

### ISSUE THREAD

**Issue by talwrii** [sshaw/git-link#73]
I sometimes want to share the branch name when I share a file. Most of the link functions seem to ignore the branch name, perhaps you could have a `defvar` to control whether to link to the branch or the commit.

**Comment by sshaw** [comment]
Hello, we have such a var: [`git-link-use-commit`](https://github.com/sshaw/git-link/tree/7142ec898f0cb97aa5d1a68da7957b4710bbfa87#git-link-use-commit). Does this help?
