### ISSUE TITLE
Add support for Savannah

### ISSUE THREAD

**Issue by leungbk** [sshaw/git-link#76]
A repo whose origin is something like https://git.savannah.gnu.org/git/emacs.git is can be viewed at https://git.savannah.gnu.org/cgit/emacs.git (note the additional 'c').

**Comment by sshaw** [comment]
Hi, this has been discussed before. See this and the link(s) it contains: https://github.com/sshaw/git-link/pull/34#issuecomment-238032402

Any thoughts based on those comments?
