### ISSUE TITLE
Proper sourcehut link

### ISSUE THREAD

**Issue by abcdw** [sshaw/git-link#77]
https://github.com/sshaw/git-link/blob/master/git-link.el#L457
For sourcehut (git.sr.ht) used the same function as for github, but it generates a link using `https://%s/%s/blob/%s/%s` pattern, while for sourcehut it should be `https://%s/%s/tree/%s/%s`, because `/blob/` provides access to raw file, while `/tree/` has ability to show exact part of the code using fragment part of address. 

As it is right now:
https://git.sr.ht/~abcdw/rde/blob/master/rde/system/install.scm#L50

As it should be:
https://git.sr.ht/~abcdw/rde/tree/master/rde/system/install.scm#L50

**Comment by sshaw** [comment]
Thanks. I also noticed that multi-line links were broken so fixed that too. 

Is the `tree` URL new or was it always there?

**Comment by abcdw** [comment]
Actually, IDK, use it not so often.

Thank you for fixes!)
